# Site settings
title: ThinkSpace
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/thinkspace" # the subpath of your site, e.g. /ThinkSpace
url: "http://thinkspace.ch" # the base hostname & protocol for your site
contact_email: "ludovic.turmel@liip.ch"
phone: +41 21 533 13 00
email: "info@thinkspace.ch"
twitter_username: liip

# Build settings
markdown: kramdown
exclude: [node_modules]
